FROM ubuntu:16.04

RUN apt-get update && \
    apt-get upgrade -y && \ 
    apt-get install -y \
	git \
	python \
	python-dev \
	python-setuptools \
	python-pip \
	libmysqlclient-dev \
	supervisor

WORKDIR '/app'

RUN pip install uwsgi

ADD requirements.txt .

RUN pip install -r requirements.txt

COPY . .

CMD ["python", "manage.py", "makemigrations"]

CMD ["python", "manage.py", "migrate"]

CMD ["gunicorn", "--bind", ":3000", "djangoapp.wsgi:application"]