#!/bin/bash
NAME="django_rog"                                 # Name of the application 
DJANGODIR=/usr/apps/django_production/django_rog            # Django project directory 
SOCKFILE=/usr/apps/django_production/django_rog/run/gunicorn.sock # we will communicte using this unix socket 
USER=root                                       # the user to run as 
GROUP=root                                    # the group to run as 
NUM_WORKERS=3                                    # how many worker processes should Gunicorn spawn 
DJANGO_SETTINGS_MODULE=django_rog.settings            # which settings file should Django use 
DJANGO_WSGI_MODULE=django_rog.wsgi                    # WSGI module name 
  
echo "Starting $NAME as `whoami`" 
  
# Activate the virtual environment 
cd $DJANGODIR 
#Source ../venv/bin/activate 
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE 
export PYTHONPATH=$DJANGODIR:$PYTHONPATH 
  
# Create the run directory if it doesn't exist 
RUNDIR=$(dirname $SOCKFILE) 
test -d $RUNDIR || mkdir -p $RUNDIR 
  
# Start your Django Unicorn 
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon) 
exec gunicorn --bind=$SOCKFILE --name $NAME --workers $NUM_WORKERS --user=$USER --group=$GROUP ${DJANGO_WSGI_MODULE}:application
 